//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCDCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCDCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geomorphic Change Detection Software.
        /// </summary>
        public static string ApplicationNameLong {
            get {
                return ResourceManager.GetString("ApplicationNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCD.
        /// </summary>
        public static string ApplicationNameShort {
            get {
                return ResourceManager.GetString("ApplicationNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Riverscapes/fis-dem-error.
        /// </summary>
        public static string FISRepositoryWebsite {
            get {
                return ResourceManager.GetString("FISRepositoryWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://gcd.joewheaton.org/.
        /// </summary>
        public static string GCDWebSiteURL {
            get {
                return ResourceManager.GetString("GCDWebSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://gcd6help.joewheaton.org/.
        /// </summary>
        public static string HelpBaseURL {
            get {
                return ResourceManager.GetString("HelpBaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://joewheaton.org.
        /// </summary>
        public static string PeopleJoeWheatonURL {
            get {
                return ResourceManager.GetString("PeopleJoeWheatonURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The horizontal decimal precision refers to the number of decimals places used to define the raster extent and cell size. This value should be the minimum number of decimal places required to accurately store the raster cell size. e.g. a cell size of 0.01m (1cm) should use a precision of 2..
        /// </summary>
        public static string PrecisionHelp {
            get {
                return ResourceManager.GetString("PrecisionHelp", resourceCulture);
            }
        }
    }
}
