//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCDCore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 0")]
        public global::System.Drawing.Color Erosion {
            get {
                return ((global::System.Drawing.Color)(this["Erosion"]));
            }
            set {
                this["Erosion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27, 63, 139")]
        public global::System.Drawing.Color Deposition {
            get {
                return ((global::System.Drawing.Color)(this["Deposition"]));
            }
            set {
                this["Deposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ValidateProjectOnLoad {
            get {
                return ((bool)(this["ValidateProjectOnLoad"]));
            }
            set {
                this["ValidateProjectOnLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempWorkspace {
            get {
                return ((string)(this["TempWorkspace"]));
            }
            set {
                this["TempWorkspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartUpWorkspaceWarning {
            get {
                return ((bool)(this["StartUpWorkspaceWarning"]));
            }
            set {
                this["StartUpWorkspaceWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearWorkspaceOnStartup {
            get {
                return ((bool)(this["ClearWorkspaceOnStartup"]));
            }
            set {
                this["ClearWorkspaceOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WarnAboutLongPaths {
            get {
                return ((bool)(this["WarnAboutLongPaths"]));
            }
            set {
                this["WarnAboutLongPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoLoadFISLibrary {
            get {
                return ((bool)(this["AutoLoadFISLibrary"]));
            }
            set {
                this["AutoLoadFISLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplyComparativeSymbology {
            get {
                return ((bool)(this["ApplyComparativeSymbology"]));
            }
            set {
                this["ApplyComparativeSymbology"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplyTransparencySymbology {
            get {
                return ((bool)(this["ApplyTransparencySymbology"]));
            }
            set {
                this["ApplyTransparencySymbology"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComparativeSymbology3dPointQuality {
            get {
                return ((bool)(this["ComparativeSymbology3dPointQuality"]));
            }
            set {
                this["ComparativeSymbology3dPointQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComparativeSymbologyInterpolationError {
            get {
                return ((bool)(this["ComparativeSymbologyInterpolationError"]));
            }
            set {
                this["ComparativeSymbologyInterpolationError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComparativeSymbologyPointDensity {
            get {
                return ((bool)(this["ComparativeSymbologyPointDensity"]));
            }
            set {
                this["ComparativeSymbologyPointDensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComparativeSymbologyDoD {
            get {
                return ((bool)(this["ComparativeSymbologyDoD"]));
            }
            set {
                this["ComparativeSymbologyDoD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComparativeSymbologyFISError {
            get {
                return ((bool)(this["ComparativeSymbologyFISError"]));
            }
            set {
                this["ComparativeSymbologyFISError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransparencyAssociatedLayers {
            get {
                return ((bool)(this["TransparencyAssociatedLayers"]));
            }
            set {
                this["TransparencyAssociatedLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransparencyAnalysesLayers {
            get {
                return ((bool)(this["TransparencyAnalysesLayers"]));
            }
            set {
                this["TransparencyAnalysesLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransparencyErrorLayers {
            get {
                return ((bool)(this["TransparencyErrorLayers"]));
            }
            set {
                this["TransparencyErrorLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int AutoTransparencyValue {
            get {
                return ((int)(this["AutoTransparencyValue"]));
            }
            set {
                this["AutoTransparencyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GeoTiff")]
        public string DefaultRasterFormat {
            get {
                return ((string)(this["DefaultRasterFormat"]));
            }
            set {
                this["DefaultRasterFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int ChartWidth {
            get {
                return ((int)(this["ChartWidth"]));
            }
            set {
                this["ChartWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int ChartHeight {
            get {
                return ((int)(this["ChartHeight"]));
            }
            set {
                this["ChartHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutomaticPyramids {
            get {
                return ((string)(this["AutomaticPyramids"]));
            }
            set {
                this["AutomaticPyramids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUsedProjectFolder {
            get {
                return ((string)(this["LastUsedProjectFolder"]));
            }
            set {
                this["LastUsedProjectFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddOutputLayersToMap {
            get {
                return ((bool)(this["AddOutputLayersToMap"]));
            }
            set {
                this["AddOutputLayersToMap"] = value;
            }
        }
    }
}
