using GCDCore.Project;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Xml.Linq;
using System.Threading.Tasks;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GCDUserInterface.My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	static internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCDUserInterface.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Add {
			get {
				object obj = ResourceManager.GetObject("Add", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap AddToMap {
			get {
				object obj = ResourceManager.GetObject("AddToMap", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap alphabetical {
			get {
				object obj = ResourceManager.GetObject("alphabetical", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap AOI {
			get {
				object obj = ResourceManager.GetObject("AOI", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap AssociatedSurfaces {
			get {
				object obj = ResourceManager.GetObject("AssociatedSurfaces", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap BrowseFolder {
			get {
				object obj = ResourceManager.GetObject("BrowseFolder", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap BudgetSeg {
			get {
				object obj = ResourceManager.GetObject("BudgetSeg", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap chart {
			get {
				object obj = ResourceManager.GetObject("chart", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Check {
			get {
				object obj = ResourceManager.GetObject("Check", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap CleanRaster {
			get {
				object obj = ResourceManager.GetObject("CleanRaster", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap CoincidentPoints {
			get {
				object obj = ResourceManager.GetObject("CoincidentPoints", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap ConcaveHull {
			get {
				object obj = ResourceManager.GetObject("ConcaveHull", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Copy {
			get {
				object obj = ResourceManager.GetObject("Copy", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap CurrentFunders {
			get {
				object obj = ResourceManager.GetObject("CurrentFunders", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap CurrentFunders2 {
			get {
				object obj = ResourceManager.GetObject("CurrentFunders2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Delete {
			get {
				object obj = ResourceManager.GetObject("Delete", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Delta {
			get {
				object obj = ResourceManager.GetObject("Delta", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap DEMSurvey {
			get {
				object obj = ResourceManager.GetObject("DEMSurvey", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Developers {
			get {
				object obj = ResourceManager.GetObject("Developers", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap DoD_Logo {
			get {
				object obj = ResourceManager.GetObject("DoD_Logo", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Excel {
			get {
				object obj = ResourceManager.GetObject("Excel", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap FISLibrary {
			get {
				object obj = ResourceManager.GetObject("FISLibrary", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap GCD {
			get {
				object obj = ResourceManager.GetObject("GCD", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap GCD_SplashLogo_200 {
			get {
				object obj = ResourceManager.GetObject("GCD_SplashLogo_200", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Help {
			get {
				object obj = ResourceManager.GetObject("Help", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Histogram {
			get {
				object obj = ResourceManager.GetObject("Histogram", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap ICRRR_Logo_100 {
			get {
				object obj = ResourceManager.GetObject("ICRRR_Logo_100", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap IdahoPower {
			get {
				object obj = ResourceManager.GetObject("IdahoPower", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap IdahoPower_63height {
			get {
				object obj = ResourceManager.GetObject("IdahoPower_63height", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap NewProject {
			get {
				object obj = ResourceManager.GetObject("NewProject", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap OpenProject {
			get {
				object obj = ResourceManager.GetObject("OpenProject", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Options {
			get {
				object obj = ResourceManager.GetObject("Options", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap PointDensity {
			get {
				object obj = ResourceManager.GetObject("PointDensity", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap polygon {
			get {
				object obj = ResourceManager.GetObject("polygon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap PreviousFunders {
			get {
				object obj = ResourceManager.GetObject("PreviousFunders", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap print {
			get {
				object obj = ResourceManager.GetObject("print", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap refresh {
			get {
				object obj = ResourceManager.GetObject("refresh", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Report {
			get {
				object obj = ResourceManager.GetObject("Report", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Reservoir {
			get {
				object obj = ResourceManager.GetObject("Reservoir", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Roughness {
			get {
				object obj = ResourceManager.GetObject("Roughness", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Save {
			get {
				object obj = ResourceManager.GetObject("Save", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap SaveGIS {
			get {
				object obj = ResourceManager.GetObject("SaveGIS", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap SelectAll {
			get {
				object obj = ResourceManager.GetObject("SelectAll", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap SelectNone {
			get {
				object obj = ResourceManager.GetObject("SelectNone", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Settings {
			get {
				object obj = ResourceManager.GetObject("Settings", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap sigma {
			get {
				object obj = ResourceManager.GetObject("sigma", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap SlopeDegree {
			get {
				object obj = ResourceManager.GetObject("SlopeDegree", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap SlopePercent {
			get {
				object obj = ResourceManager.GetObject("SlopePercent", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap TopCat {
			get {
				object obj = ResourceManager.GetObject("TopCat", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized string similar to Online help for this tool..
		///</summary>
		static internal string ttpHelp {
			get { return ResourceManager.GetString("ttpHelp", resourceCulture); }
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap USGS {
			get {
				object obj = ResourceManager.GetObject("USGS", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap USUlogo {
			get {
				object obj = ResourceManager.GetObject("USUlogo", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}
	}
}
