'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AddOutputLayersToMap() As Boolean
            Get
                Return CType(Me("AddOutputLayersToMap"),Boolean)
            End Get
            Set
                Me("AddOutputLayersToMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastUsedProjectFolder() As String
            Get
                Return CType(Me("LastUsedProjectFolder"),String)
            End Get
            Set
                Me("LastUsedProjectFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property ChartHeight() As Integer
            Get
                Return CType(Me("ChartHeight"),Integer)
            End Get
            Set
                Me("ChartHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property ChartWidth() As Integer
            Get
                Return CType(Me("ChartWidth"),Integer)
            End Get
            Set
                Me("ChartWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ValidateProjectOnLoad() As Boolean
            Get
                Return CType(Me("ValidateProjectOnLoad"),Boolean)
            End Get
            Set
                Me("ValidateProjectOnLoad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ClearWorkspaceOnStartup() As Boolean
            Get
                Return CType(Me("ClearWorkspaceOnStartup"),Boolean)
            End Get
            Set
                Me("ClearWorkspaceOnStartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AddInputLayersToMap() As Boolean
            Get
                Return CType(Me("AddInputLayersToMap"),Boolean)
            End Get
            Set
                Me("AddInputLayersToMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarnAboutLongPaths() As Boolean
            Get
                Return CType(Me("WarnAboutLongPaths"),Boolean)
            End Get
            Set
                Me("WarnAboutLongPaths") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoLoadFISLibrary() As Boolean
            Get
                Return CType(Me("AutoLoadFISLibrary"),Boolean)
            End Get
            Set
                Me("AutoLoadFISLibrary") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ApplyComparativeSymbology() As Boolean
            Get
                Return CType(Me("ApplyComparativeSymbology"),Boolean)
            End Get
            Set
                Me("ApplyComparativeSymbology") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ApplyTransparencySymbology() As Boolean
            Get
                Return CType(Me("ApplyTransparencySymbology"),Boolean)
            End Get
            Set
                Me("ApplyTransparencySymbology") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ComparativeSymbology3dPointQuality() As Boolean
            Get
                Return CType(Me("ComparativeSymbology3dPointQuality"),Boolean)
            End Get
            Set
                Me("ComparativeSymbology3dPointQuality") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ComparativeSymbologyInterpolationError() As Boolean
            Get
                Return CType(Me("ComparativeSymbologyInterpolationError"),Boolean)
            End Get
            Set
                Me("ComparativeSymbologyInterpolationError") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ComparativeSymbologyPointDensity() As Boolean
            Get
                Return CType(Me("ComparativeSymbologyPointDensity"),Boolean)
            End Get
            Set
                Me("ComparativeSymbologyPointDensity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ComparativeSymbologyDoD() As Boolean
            Get
                Return CType(Me("ComparativeSymbologyDoD"),Boolean)
            End Get
            Set
                Me("ComparativeSymbologyDoD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ComparativeSymbologyFISError() As Boolean
            Get
                Return CType(Me("ComparativeSymbologyFISError"),Boolean)
            End Get
            Set
                Me("ComparativeSymbologyFISError") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property StartUpWorkspaceWarning() As Boolean
            Get
                Return CType(Me("StartUpWorkspaceWarning"),Boolean)
            End Get
            Set
                Me("StartUpWorkspaceWarning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TransparencyAssociatedLayers() As Boolean
            Get
                Return CType(Me("TransparencyAssociatedLayers"),Boolean)
            End Get
            Set
                Me("TransparencyAssociatedLayers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TransparencyAnalysesLayers() As Boolean
            Get
                Return CType(Me("TransparencyAnalysesLayers"),Boolean)
            End Get
            Set
                Me("TransparencyAnalysesLayers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TransparencyErrorLayers() As Boolean
            Get
                Return CType(Me("TransparencyErrorLayers"),Boolean)
            End Get
            Set
                Me("TransparencyErrorLayers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property AutoTransparencyValue() As Double
            Get
                Return CType(Me("AutoTransparencyValue"),Double)
            End Get
            Set
                Me("AutoTransparencyValue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ESRI GeoTIFF")>  _
        Public Property DefaultRasterFormat() As String
            Get
                Return CType(Me("DefaultRasterFormat"),String)
            End Get
            Set
                Me("DefaultRasterFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutomaticPyramids() As Boolean
            Get
                Return CType(Me("AutomaticPyramids"),Boolean)
            End Get
            Set
                Me("AutomaticPyramids") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TempWorkspace() As String
            Get
                Return CType(Me("TempWorkspace"),String)
            End Get
            Set
                Me("TempWorkspace") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192, 0, 0")>  _
        Public Property Erosion() As Global.System.Drawing.Color
            Get
                Return CType(Me("Erosion"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Erosion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("27, 63, 139")>  _
        Public Property Depsoition() As Global.System.Drawing.Color
            Get
                Return CType(Me("Depsoition"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Depsoition") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GCDLib.My.MySettings
            Get
                Return Global.GCDLib.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
