# Site title will be used everywhere
title: Geomorphic Change Detection Software
description: > # this means to ignore newlines until "baseurl:"
  Online help and documentation site for the GCD

# Final root url of the site. No ending slash. No subdirectory
url: http://gcd.riverscapes.xyz
# If the site is in a subdirectory you should do it like this: "/subdirectory". Otherwise ""
# baseurl: "/gcd"
# When serving locally what port should we use:
port: 4001
google_analytics: UA-60121403-8

# Syntax highlighter.
highlighter: rouge

# Choosing "default" layout means we don't need a "layout:default" in all our 
# front matter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Files/Folders to exclude from publishing
exclude:
  - src
  - LICENSE
  - README.md
  - _config.yml
  - vendor
  - Gemfile* 

# These are theme settings that will be used to turn features on and off
# They are not part of Jekyll, they are entirely custom.
settings:
  # Turn the automatically generated page contents on and off
  autoPageContents:
    active: true
    onHome: false
  # Options for the sidebar menu      
  sideMenu:
    homeItem: true
    startExpanded: false
  # Arbitrary multi-level topbar menu
  # IF you don't need this just comment out everything below
  # ----------------------------------
  topmenu:
    - title: "Riverscapes Consortium"
      url: http://riverscapes.xyz
    - title: "Tools"
      url: https://riverscapes.xyz/Tools/
    - title: "Data"
      url: https://data.riverscapes.xyz
    - title: "Maps"
      url: https://maps.riverscapes.xyz

collections:
  releasenotes:
    output: true

# Redirecting from apps can be tricky so we use a key-value system
# key: must be in the set [A-Za-z0-9_] (no spaces, no dashes)
# url: must be relative url, no leading slash.
# 
# The url you have to call is: http://siteurl.com/baseurl/?APPKEY=KEY1
# ---------------------------------------------------------------
AppRedirects:
  - key: NewProject
    url: Help/project-menu/new-project.html
  - key: ProjectProperties
    url: Help/project-menu/new-project.html
  - key: frmOptions
    url: Help/customize-menu/options.html
  - key: frmFISLibrary
    url: Help/customize-menu/fis-library.html
  - key: frmFISProperties
    url: Help/customize-menu/fis-library.html
  - key: frmSurfaceProperties
    url: index.html
  - key: frmPointDensity
    url: Help/Inputs/associated-surfaces.html#calculating-point-density
  - key: frmAssociatedSurface
    url: Help/Inputs/associated-surfaces.html
  - key: frmSingleMethodError
    url: Help/Inputs/error-surfaces.html
  - key: frmMultiMethodError
    url: Help/Inputs/error-surfaces.html#multi-method-error-surfaces
  - key: frmLinearExtractionProperties
    url: Help/Inputs/linear-extractions.html
  - key: frmReferenceSurfaceFromDEMs
    url: Help/Inputs/reference-surfaces.html#reference-surfaces-from-dem-surveys
  - key: frmReferenceSurfaceFromConstant
    url: Help/Inputs/reference-surfaces.html#uniform-reference-surfaces
  - key: frmRefErrorSurface
    url: Help/Inputs/reference-surfaces.html#reference-error-surfaces
  - key: frmMaskProperties
    url: Help/Inputs/Masks/regular-masks.html
  - key: frmDirectionalMaskProps
    url: Help/Inputs/Masks/directional-masks.html
  - key: frmAOIProperties
    url: Help/Inputs/Masks/aoi.html
  - key: frmProfileRouteProperties
    url: Help/Inputs/profile-routes.html
  - key: frmDoDProperties
    url: Help/Analyses/Change_Detection/change-detection.html
  - key: frmBatchDoD
    url: Help/Analyses/Change_Detection/batch-change-detection.html
  - key: frmMultiEpoch
    url: Help/Analyses/Change_Detection/multiple-epoch.html
  - key: frmDoDResults
    url: Help/Analyses/Change_Detection/change-detection-results.html
  - key: frmDoDSummaryProperties
    url: Help/Analyses/Change_Detection/change-detection-results.html#customize-display-settings
  - key: frmBudgetSegProperties
    url: Help/Analyses/Budget_Segregation/budget-segregation.html
  - key: frmBudgetSegResults
    url: Help/Analyses/Budget_Segregation/budget_segregation_results.html
  - key: frmMorpProperties
    url: Help/Analyses/Change_Detection/morphological.html
  - key: frmMorphResults
    url: Help/Analyses/Change_Detection/morphological.html#view-morphological-analysis-results
  - key: frmInterComparisonProperties
    url: Help/Analyses/Change_Detection/intercomparison.html

remote_theme: Riverscapes/riverscapes-jekyll-theme
plugins:
  - jekyll-remote-theme 
